all: 
	gcc -std=c11 -o project src/binheap.h src/binheap.c src/constants.h src/graph.h src/graph.c src/linkedlist.h src/linkedlist.c src/macros.h src/unfnd.h src/unfnd.c src/utils.h src/utils.c src/binomialheap.h src/binomialheap.c src/main.c -lm
	
clean:
	rm ./project